### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by vwkd** [alwinb/reurl#4]
It would be great if the module were published to NPM such that using it in Node would become easier. Alternatively one could maybe try out [GitHub Packages](https://github.com/features/packages) which probably would be easier since the module already lives on GitHub.

I saw that there is already a `make all` command to build a minified `dist/reurl.min.js` file. It would only remain to publish it.

Currently, using reurl in Node is a bit cumbersome. One can import from GitHub though this doesn't download the minified build version but the whole GitHub repository. In NPM CLI it looks like this.

```sh
npm install alwinb/reurl
```

But this uses the latest commit, so to pin to a specify version, one needs to remember to use something like

```sh
npm install alwinb/reurl#v1.0.0rc
```

for a commit-ish hash. This works, though afaik it's not as robust as the NPM registry, because NPM CLI doesn't do integrity checks for non-NPM packages. In other words, if the content behind the URL somehow changed NPM CLI would still happily try to download it. Granted this is unlikely, and probably would only happen for commit hash collisions or garbage collected commits (not sure if GitHub does protect against that?). Also not sure if Yarn locks non-NPM dependencies?

I haven't used GitHub Registry yet, so I'm not sure how easy it is to use (I think it requires authentication for installing packages?) and if NPM properly does integrity checks.

**Comment by alwinb** [comment]
Ah, so teach me!

It is on npm at https://www.npmjs.com/package/reurl, so I just use `npm i reurl`. 

The Makefile is something I personally use (and may be a bit unusual) for creating a minified bundle, so no need to call make to use the reurl package on npm. 

Are you suggesting to publish the minified version as well, in addition to the current package?

**Comment by vwkd** [comment]
Oh... I should check before I speak. 🤦 Not sure why I never checked. Maybe reading the README without a way to install it via `npm install xyz` made me automatically assume it was missing... Too much automatic thinking. Sorry!

Also for minification, I think you're right. I didn't think about it much after seeing the build command. Some Google responses suggest minification doesn't buy anything on the server, but does make debugging more difficult. And module CDNs like Skypack do minification as part of their pipeline, so they can optimise it to use the latest algorithms.

Sorry! Will close this and get myself some glasses...

**Comment by alwinb** [comment]
Oh don't worry, and maybe I should add that to the README.
