### ISSUE TITLE
Document Node.JS usage with examples

### ISSUE THREAD

**Issue by jsepia** [alwinb/reurl#7]
I want to use the `Url` class in a Node.JS project. In order to accomplish this, I need to know how to import it. This depends on how the `reurl` NPM module exports the `Url` class.

```javascript
// named export
import { Url } from 'reurl'

// default export
import Url from 'reurl'

// workaround if the syntax above doesn't work
import * as Url from 'reurl'

// commonjs syntax
const Url = require('reurl').Url
```

The README states this:

> The ReUrl library exposes an Url class and a RawUrl class with an identical API.

but does not specify how these classes are exposed to consumers. An example would be helpful.

**Comment by alwinb** [comment]
Thank you for taking the time and effort to make these changes. I appreciate it.
